/**
 * SAP Service Layer writer - creates Delivery Notes + A/R Invoices in SAP
 * by re-using the existing sales orders.
 *
 * SAFETY:
 *   - Defaults to DRY-RUN mode (no actual write happens unless you pass dryRun:false).
 *   - Logs every payload to backend/logs/sap-writes.log so you can audit.
 *   - Refuses to write if SAP_SERVICE_LAYER_URL is missing.
 *
 * To enable real writes, set in backend/.env:
 *   SAP_SERVICE_LAYER_URL=https://192.168.0.220:50000/b1s/v1
 *   SAP_SERVICE_LAYER_USER=manager
 *   SAP_SERVICE_LAYER_PASSWORD=...
 *   SAP_SERVICE_LAYER_COMPANY_A=SAP_OIG
 *   SAP_SERVICE_LAYER_COMPANY_B=SAP_Unico
 *   SAP_WRITE_ENABLED=true              # master safety switch
 */
import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const LOG_FILE = path.resolve(__dirname, '..', '..', 'logs', 'sap-writes.log');

// Track session cookies per company
const sessions = new Map(); // 'A' | 'B' -> { cookie, expiresAt }

function logWrite(line) {
  try {
    fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });
    fs.appendFileSync(LOG_FILE, `[${new Date().toISOString()}] ${line}\n`);
  } catch {}
}

function getCompanyDb(code) {
  return code === 'A'
    ? process.env.SAP_SERVICE_LAYER_COMPANY_A || process.env.SAP_SQL_DB_A
    : process.env.SAP_SERVICE_LAYER_COMPANY_B || process.env.SAP_SQL_DB_B;
}

const slUrl = () => process.env.SAP_SERVICE_LAYER_URL || '';
const slUser = () => process.env.SAP_SERVICE_LAYER_USER || '';
const slPass = () => process.env.SAP_SERVICE_LAYER_PASSWORD || '';
const isWriteEnabled = () => process.env.SAP_WRITE_ENABLED === 'true';

const agent = new https.Agent({ rejectUnauthorized: false });

async function login(companyCode) {
  const existing = sessions.get(companyCode);
  if (existing && existing.expiresAt > Date.now()) return existing.cookie;
  const body = JSON.stringify({
    UserName: slUser(),
    Password: slPass(),
    CompanyDB: getCompanyDb(companyCode),
  });
  const res = await fetch(`${slUrl()}/Login`, {
    method: 'POST',
    body,
    headers: { 'Content-Type': 'application/json' },
    // @ts-ignore - node fetch supports agent through dispatcher in newer versions; for older versions use https module
    agent,
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`SAP Login failed (${res.status}): ${txt}`);
  }
  const cookie = res.headers.get('set-cookie') || '';
  // SAP sessions last 30 mins by default
  sessions.set(companyCode, { cookie, expiresAt: Date.now() + 25 * 60 * 1000 });
  return cookie;
}

async function postSAP(companyCode, endpoint, payload) {
  const cookie = await login(companyCode);
  const res = await fetch(`${slUrl()}/${endpoint}`, {
    method: 'POST',
    body: JSON.stringify(payload),
    headers: { 'Content-Type': 'application/json', Cookie: cookie },
    agent,
  });
  const text = await res.text();
  let json;
  try { json = JSON.parse(text); } catch { json = { raw: text }; }
  if (!res.ok) {
    throw new Error(`SAP ${endpoint} failed (${res.status}): ${text.slice(0, 300)}`);
  }
  return json;
}

/**
 * Build a SAP Delivery Note payload from one of our local DN docs.
 * The local doc has SourceOrders[*].SapDocEntry referencing the original sales orders.
 */
function buildDnPayload(dn) {
  return {
    CardCode: dn.SapCardCode,
    DocDate: dn.DeliveryDate,
    DocDueDate: dn.DeliveryDate,
    Comments: dn.Notes || `Auto-generated by Logistics Hub - ${dn.DocNumber}`,
    // Each source order line becomes a DN line via BaseEntry/BaseLine reference
    DocumentLines: (dn.SourceOrders || []).flatMap((src) =>
      (src.lines || [{}]).map((ln, idx) => ({
        BaseType: 17,                      // 17 = sales order
        BaseEntry: src.SapDocEntry,
        BaseLine: ln.LineNum != null ? ln.LineNum : idx,
        Quantity: ln.Quantity || ln.OpenQty,
      }))
    ),
  };
}

function buildInvoicePayload(invoice, dn) {
  return {
    CardCode: invoice.SapCardCode,
    DocDate: new Date().toISOString().slice(0, 10),
    DocDueDate: new Date().toISOString().slice(0, 10),
    Comments: `Auto-generated from DN ${dn?.DocNumber || ''}`,
    DocumentLines: dn?.SourceOrders?.flatMap((src) =>
      (src.lines || [{}]).map((ln, idx) => ({
        BaseType: 15,                      // 15 = delivery note
        BaseEntry: dn.SapDeliveryDocEntry,
        BaseLine: ln.LineNum != null ? ln.LineNum : idx,
      }))
    ) || [],
  };
}

/**
 * Push a single Delivery Note to SAP.
 * Returns { ok, sapDocEntry, sapDocNum, dryRun, payload }.
 */
export async function writeDeliveryNote(dn, options = {}) {
  const dryRun = options.dryRun !== false; // default DRY-RUN
  const payload = buildDnPayload(dn);
  logWrite(`DN ${dn.DocNumber} (${dn.CompanyCode}): ${dryRun ? 'DRY-RUN' : 'LIVE'} payload=${JSON.stringify(payload)}`);

  if (dryRun || !isWriteEnabled() || !slUrl()) {
    return {
      ok: true,
      dryRun: true,
      // No DocEntry available in dry-run — the document was NOT written to
      // SAP, so there is no real DocEntry to surface. Returning null forces
      // the caller's `if (result.sapDocEntry)` guards to skip the
      // "save SAP DocEntry on the local DN" step, which is exactly what we
      // want — see fix(docs): remove fake SapDeliveryDocEntry assignment
      // (Phase A1).
      sapDocEntry: null,
      sapDocNum: null,
      payload,
      reason: !slUrl()
        ? 'SAP_SERVICE_LAYER_URL not configured'
        : !isWriteEnabled()
          ? 'SAP_WRITE_ENABLED is not true'
          : 'options.dryRun',
    };
  }

  try {
    const result = await postSAP(dn.CompanyCode, 'DeliveryNotes', payload);
    return {
      ok: true,
      dryRun: false,
      sapDocEntry: result.DocEntry,
      sapDocNum: result.DocNum,
      payload,
      result,
    };
  } catch (err) {
    logWrite(`DN ${dn.DocNumber} ERROR: ${err.message}`);
    return { ok: false, dryRun: false, error: err.message, payload };
  }
}

/**
 * Push a single Invoice to SAP, based on a previously-written DN.
 */
export async function writeInvoice(invoice, dn, options = {}) {
  const dryRun = options.dryRun !== false;
  const payload = buildInvoicePayload(invoice, dn);
  logWrite(`INV ${invoice.DocNumber} (${invoice.CompanyCode}): ${dryRun ? 'DRY-RUN' : 'LIVE'} payload=${JSON.stringify(payload)}`);

  if (dryRun || !isWriteEnabled() || !slUrl()) {
    return {
      ok: true,
      dryRun: true,
      // Mirror of writeDeliveryNote: no DocEntry in dry-run mode — the
      // invoice was not actually created in SAP, so we MUST NOT surface a
      // numeric DocEntry that the caller would persist into
      // invoice.SapInvoiceDocEntry. See A1 rationale above.
      sapDocEntry: null,
      sapDocNum: null,
      payload,
      reason: !slUrl()
        ? 'SAP_SERVICE_LAYER_URL not configured'
        : !isWriteEnabled()
          ? 'SAP_WRITE_ENABLED is not true'
          : 'options.dryRun',
    };
  }

  try {
    const result = await postSAP(invoice.CompanyCode, 'Invoices', payload);
    return {
      ok: true,
      dryRun: false,
      sapDocEntry: result.DocEntry,
      sapDocNum: result.DocNum,
      payload,
      result,
    };
  } catch (err) {
    logWrite(`INV ${invoice.DocNumber} ERROR: ${err.message}`);
    return { ok: false, dryRun: false, error: err.message, payload };
  }
}

/** Status of the SAP writer for the UI banner. */
export function getWriterStatus() {
  return {
    serviceLayerConfigured: !!slUrl(),
    writeEnabled: isWriteEnabled(),
    canWrite: !!slUrl() && isWriteEnabled(),
    mode: !slUrl() || !isWriteEnabled() ? 'DRY-RUN' : 'LIVE',
    logFile: LOG_FILE,
  };
}
