/**
 * SAP Service Layer writer - creates Delivery Notes + A/R Invoices in SAP
 * by re-using the existing sales orders.
 *
 * SAFETY:
 *   - Defaults to DRY-RUN mode (no actual write happens unless you pass dryRun:false).
 *   - Logs every payload to backend/logs/sap-writes.log so you can audit.
 *   - Refuses to write if SAP_SERVICE_LAYER_URL is missing.
 *
 * To enable real writes, set in backend/.env:
 *   SAP_SERVICE_LAYER_URL=https://192.168.0.220:50000/b1s/v1
 *   SAP_SERVICE_LAYER_USER=manager
 *   SAP_SERVICE_LAYER_PASSWORD=...
 *   SAP_SERVICE_LAYER_COMPANY_A=SAP_OIG
 *   SAP_SERVICE_LAYER_COMPANY_B=SAP_Unico
 *   SAP_WRITE_ENABLED=true              # master safety switch
 */
import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const LOG_FILE = path.resolve(__dirname, '..', '..', 'logs', 'sap-writes.log');

// Track session cookies per company
const sessions = new Map(); // 'A' | 'B' -> { cookie, expiresAt }

function logWrite(line) {
  try {
    fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });
    fs.appendFileSync(LOG_FILE, `[${new Date().toISOString()}] ${line}\n`);
  } catch {}
}

/**
 * P1 (2026-05-16): the canonical env names in .env.example are SAP_SL_*
 * (SAP_SL_URL, SAP_SL_USERNAME, SAP_SL_PASSWORD, SAP_SL_COMPANY_DB_A/B),
 * but this file was originally written against SAP_SERVICE_LAYER_* names
 * that never made it into .env or .env.example. Result: even with
 * SAP_WRITE_ENABLED=true, slUrl()/slUser()/slPass() all returned '' and
 * login() would silently fail — a hidden safety net but also a config
 * blocker that prevented even deliberate test-DB writes from working.
 *
 * Fix: read SAP_SL_* first (matches .env / .env.example), fall back to
 * SAP_SERVICE_LAYER_* (legacy), and for the company DB also fall back to
 * SAP_SQL_DB_A/B as a last resort. Backwards-compat: any env that worked
 * before keeps working.
 */
function getCompanyDb(code) {
  return code === 'A'
    ? process.env.SAP_SL_COMPANY_DB_A
        || process.env.SAP_SERVICE_LAYER_COMPANY_A
        || process.env.SAP_SQL_DB_A
    : process.env.SAP_SL_COMPANY_DB_B
        || process.env.SAP_SERVICE_LAYER_COMPANY_B
        || process.env.SAP_SQL_DB_B;
}

const slUrl  = () => process.env.SAP_SL_URL      || process.env.SAP_SERVICE_LAYER_URL      || '';
const slUser = () => process.env.SAP_SL_USERNAME || process.env.SAP_SERVICE_LAYER_USER     || '';
const slPass = () => process.env.SAP_SL_PASSWORD || process.env.SAP_SERVICE_LAYER_PASSWORD || '';
const isWriteEnabled = () => process.env.SAP_WRITE_ENABLED === 'true';

const agent = new https.Agent({ rejectUnauthorized: false });

async function login(companyCode) {
  const existing = sessions.get(companyCode);
  if (existing && existing.expiresAt > Date.now()) return existing.cookie;
  const body = JSON.stringify({
    UserName: slUser(),
    Password: slPass(),
    CompanyDB: getCompanyDb(companyCode),
  });
  const res = await fetch(`${slUrl()}/Login`, {
    method: 'POST',
    body,
    headers: { 'Content-Type': 'application/json' },
    // @ts-ignore - node fetch supports agent through dispatcher in newer versions; for older versions use https module
    agent,
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`SAP Login failed (${res.status}): ${txt}`);
  }
  const cookie = res.headers.get('set-cookie') || '';
  // SAP sessions last 30 mins by default
  sessions.set(companyCode, { cookie, expiresAt: Date.now() + 25 * 60 * 1000 });
  return cookie;
}

async function postSAP(companyCode, endpoint, payload) {
  const cookie = await login(companyCode);
  const res = await fetch(`${slUrl()}/${endpoint}`, {
    method: 'POST',
    body: JSON.stringify(payload),
    headers: { 'Content-Type': 'application/json', Cookie: cookie },
    agent,
  });
  const text = await res.text();
  let json;
  try { json = JSON.parse(text); } catch { json = { raw: text }; }
  if (!res.ok) {
    throw new Error(`SAP ${endpoint} failed (${res.status}): ${text.slice(0, 300)}`);
  }
  return json;
}

/**
 * Build a SAP Delivery Note payload from one of our local DN docs.
 * The local doc has SourceOrders[*].SapDocEntry referencing the original sales orders.
 */
function buildDnPayload(dn) {
  return {
    CardCode: dn.SapCardCode,
    DocDate: dn.DeliveryDate,
    DocDueDate: dn.DeliveryDate,
    Comments: dn.Notes || `Auto-generated by Logistics Hub - ${dn.DocNumber}`,
    // Each source order line becomes a DN line via BaseEntry/BaseLine reference
    DocumentLines: (dn.SourceOrders || []).flatMap((src) =>
      (src.lines || [{}]).map((ln, idx) => ({
        BaseType: 17,                      // 17 = sales order
        BaseEntry: src.SapDocEntry,
        BaseLine: ln.LineNum != null ? ln.LineNum : idx,
        Quantity: ln.Quantity || ln.OpenQty,
      }))
    ),
  };
}

/**
 * A2d (2026-05-19): the Invoice payload has two valid shapes depending on
 * whether the parent DN has already been written to SAP (live mode) or not
 * (dry-run mode where dn.SapDeliveryDocEntry is null).
 *
 *   Live mode  (dn?.SapDeliveryDocEntry truthy):
 *     DocumentLines reference the DN via BaseType=15 + BaseEntry/BaseLine.
 *     SAP copies item/quantity/price from the source DN.
 *
 *   Dry-run / standalone mode (no SapDeliveryDocEntry):
 *     DocumentLines list the picked items directly (ItemCode + Quantity).
 *     Lets the operator see exactly what would be sent to SAP without
 *     requiring a real DN DocEntry that doesn't exist yet in dry-run.
 *
 *   No DN at all (rare INV-without-DN policy path):
 *     Falls back to invoice.Lines (built directly from picked lines in
 *     flushAggregateDocsForRun's INV-only branch).
 *
 * Exported as _buildInvoicePayload for unit tests in
 * sapWriter.invoicePayload.test.js. Internal callers use it as
 * buildInvoicePayload(...) below.
 */
export function _buildInvoicePayload(invoice, dn) {
  const today = new Date().toISOString().slice(0, 10);
  const base = {
    CardCode: invoice.SapCardCode,
    DocDate: today,
    DocDueDate: today,
    Comments: `Auto-generated from DN ${dn?.DocNumber || ''}`.trim(),
  };

  // Live mode: reference the SAP-side DN.
  if (dn?.SapDeliveryDocEntry) {
    const lines = (dn.SourceOrders || []).flatMap((src) =>
      (src.lines || [{}]).map((ln, idx) => ({
        BaseType: 15,                      // 15 = delivery note
        BaseEntry: dn.SapDeliveryDocEntry,
        BaseLine: ln.LineNum != null ? ln.LineNum : idx,
      }))
    );
    return { ...base, DocumentLines: lines };
  }

  // Standalone mode: emit ItemCode/Quantity from picked lines. Prefer dn.Lines
  // (the aggregated per-item view from flushAggregateDocsForRun) and fall back
  // to invoice.Lines for the INV-without-DN branch.
  const pickedLines = (dn?.Lines && dn.Lines.length) ? dn.Lines : (invoice.Lines || []);
  const documentLines = pickedLines.map((ln) => ({
    ItemCode: ln.ItemCode,
    Quantity: ln.Picked != null ? ln.Picked : ln.Quantity,
  }));
  return { ...base, DocumentLines: documentLines };
}

function buildInvoicePayload(invoice, dn) {
  return _buildInvoicePayload(invoice, dn);
}

/**
 * Push a single Delivery Note to SAP.
 * Returns { ok, sapDocEntry, sapDocNum, dryRun, payload }.
 */
export async function writeDeliveryNote(dn, options = {}) {
  const dryRun = options.dryRun !== false; // default DRY-RUN
  const payload = buildDnPayload(dn);
  logWrite(`DN ${dn.DocNumber} (${dn.CompanyCode}): ${dryRun ? 'DRY-RUN' : 'LIVE'} payload=${JSON.stringify(payload)}`);

  if (dryRun || !isWriteEnabled() || !slUrl()) {
    return {
      ok: true,
      dryRun: true,
      // No DocEntry available in dry-run — the document was NOT written to
      // SAP, so there is no real DocEntry to surface. Returning null forces
      // the caller's `if (result.sapDocEntry)` guards to skip the
      // "save SAP DocEntry on the local DN" step, which is exactly what we
      // want — see fix(docs): remove fake SapDeliveryDocEntry assignment
      // (Phase A1).
      sapDocEntry: null,
      sapDocNum: null,
      payload,
      reason: !slUrl()
        ? 'SAP_SERVICE_LAYER_URL not configured'
        : !isWriteEnabled()
          ? 'SAP_WRITE_ENABLED is not true'
          : 'options.dryRun',
    };
  }

  // A2c-1 per-request gate. Throws 503 if env has drifted since startup
  // and the target DB is no longer in SAP_LIVE_WRITE_DB_WHITELIST.
  try {
    assertLiveWriteAllowedAtRequest();
  } catch (err) {
    logWrite(`DN ${dn.DocNumber} GATE BLOCKED: ${err.message}`);
    return { ok: false, dryRun: false, error: err.message, code: err.code, payload };
  }

  try {
    const result = await postSAP(dn.CompanyCode, 'DeliveryNotes', payload);
    return {
      ok: true,
      dryRun: false,
      sapDocEntry: result.DocEntry,
      sapDocNum: result.DocNum,
      payload,
      result,
    };
  } catch (err) {
    logWrite(`DN ${dn.DocNumber} ERROR: ${err.message}`);
    return { ok: false, dryRun: false, error: err.message, payload };
  }
}

/**
 * Push a single Invoice to SAP, based on a previously-written DN.
 */
export async function writeInvoice(invoice, dn, options = {}) {
  const dryRun = options.dryRun !== false;
  const payload = buildInvoicePayload(invoice, dn);
  logWrite(`INV ${invoice.DocNumber} (${invoice.CompanyCode}): ${dryRun ? 'DRY-RUN' : 'LIVE'} payload=${JSON.stringify(payload)}`);

  if (dryRun || !isWriteEnabled() || !slUrl()) {
    return {
      ok: true,
      dryRun: true,
      // Mirror of writeDeliveryNote: no DocEntry in dry-run mode — the
      // invoice was not actually created in SAP, so we MUST NOT surface a
      // numeric DocEntry that the caller would persist into
      // invoice.SapInvoiceDocEntry. See A1 rationale above.
      sapDocEntry: null,
      sapDocNum: null,
      payload,
      reason: !slUrl()
        ? 'SAP_SERVICE_LAYER_URL not configured'
        : !isWriteEnabled()
          ? 'SAP_WRITE_ENABLED is not true'
          : 'options.dryRun',
    };
  }

  // A2c-1 per-request gate (mirror of writeDeliveryNote).
  try {
    assertLiveWriteAllowedAtRequest();
  } catch (err) {
    logWrite(`INV ${invoice.DocNumber} GATE BLOCKED: ${err.message}`);
    return { ok: false, dryRun: false, error: err.message, code: err.code, payload };
  }

  try {
    const result = await postSAP(invoice.CompanyCode, 'Invoices', payload);
    return {
      ok: true,
      dryRun: false,
      sapDocEntry: result.DocEntry,
      sapDocNum: result.DocNum,
      payload,
      result,
    };
  } catch (err) {
    logWrite(`INV ${invoice.DocNumber} ERROR: ${err.message}`);
    return { ok: false, dryRun: false, error: err.message, payload };
  }
}

/** Status of the SAP writer for the UI banner. */
export function getWriterStatus() {
  return {
    serviceLayerConfigured: !!slUrl(),
    writeEnabled: isWriteEnabled(),
    canWrite: !!slUrl() && isWriteEnabled(),
    mode: !slUrl() || !isWriteEnabled() ? 'DRY-RUN' : 'LIVE',
    logFile: LOG_FILE,
    whitelist: parseWhitelist(process.env.SAP_LIVE_WRITE_DB_WHITELIST),
  };
}

/**
 * A2c-1 / Bug 3 (2026-05-16): SAP_LIVE_WRITE_DB_WHITELIST gate.
 *
 * The pure helpers now live in backend/src/services/sap/writeWhitelist.js
 * so both this file AND backend/src/services/sap/serviceLayer.js can use
 * the same logic. See that module's header for the full contract.
 *
 * We re-export parseWhitelist + _checkLiveWriteWhitelist here for
 * backward-compatibility: existing unit tests (sapWriter.whitelist.test.js)
 * and server.js startup gate import them via this module's path.
 */
export {
  parseWhitelist,
  _checkLiveWriteWhitelist,
} from '../services/sap/writeWhitelist.js';

// A2g-FIX-WRITER-STATUS (2026-05-20): the `export {} from` block above
// re-exports parseWhitelist to outside consumers (tests, server.js gate),
// but does NOT bring it into the local module scope. getWriterStatus()
// directly calls parseWhitelist(...) — without this import line the
// runtime hits ReferenceError on every /api/sap/writer/status request,
// which manifested as a hung A2f banner once a real admin token reached
// the endpoint. Adding parseWhitelist to the named import keeps the
// re-export intact (external imports still work) and gives the local
// function the binding it actually uses.
import { assertLiveWriteAllowed, parseWhitelist } from '../services/sap/writeWhitelist.js';

/**
 * Per-request gate for writeDeliveryNote() / writeInvoice(). Reads env at
 * call time (not import time) so a runtime SAP_LIVE_WRITE_DB_WHITELIST or
 * SAP_SL_COMPANY_DB_* change takes effect immediately. Throws .status=503
 * on failure. No-op when SAP_WRITE_ENABLED!=true (dry-run paths skip).
 */
function assertLiveWriteAllowedAtRequest() {
  assertLiveWriteAllowed({
    writeEnabled: isWriteEnabled(),
    whitelist: process.env.SAP_LIVE_WRITE_DB_WHITELIST,
    dbA: getCompanyDb('A'),
    dbB: getCompanyDb('B'),
  });
}
